# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84306fdc536463c6c4680ba95ea94e694e6b864068f3064104db7fdc5931e410c813bf0824ce14eef722c842b36006845b6243ae44bbdd2c314a161c7c5cedd0

test:
  secret_key_base: f00538169ce883da35aa8c79c813a111db6d3bebdb5f839189b3692d5c7a33159205402e09743029bcf5e1640a17e9ee2c5e12c9189a1a255ba0a24c02008ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
